### ISSUE TITLE
import failed with error:DLL load failed while importing libtriton

### ISSUE THREAD

**Issue by czcz1024** [lujiazho/ComfyUI-CatvtonFluxWrapper#10]
Traceback (most recent call last):
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\utils\import_utils.py", line 853, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "D:\ai\ComfyUI\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\loaders\lora_pipeline.py", line 36, in <module>
    from .lora_base import LoraBaseMixin
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\loaders\lora_base.py", line 27, in <module>
    from ..models.modeling_utils import ModelMixin, load_state_dict
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\models\modeling_utils.py", line 35, in <module>
    from ..quantizers import DiffusersAutoQuantizer, DiffusersQuantizer
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\quantizers\__init__.py", line 15, in <module>
    from .auto import DiffusersAutoQuantizer
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\quantizers\auto.py", line 21, in <module>
    from .bitsandbytes import BnB4BitDiffusersQuantizer, BnB8BitDiffusersQuantizer
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\quantizers\bitsandbytes\__init__.py", line 2, in <module>
    from .utils import dequantize_and_replace, dequantize_bnb_weight, replace_with_bnb_linear
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\quantizers\bitsandbytes\utils.py", line 32, in <module>
    import bitsandbytes as bnb
  File "D:\ai\ComfyUI\python\lib\site-packages\bitsandbytes\__init__.py", line 15, in <module>
    from .nn import modules
  File "D:\ai\ComfyUI\python\lib\site-packages\bitsandbytes\nn\__init__.py", line 21, in <module>
    from .triton_based_modules import (
  File "D:\ai\ComfyUI\python\lib\site-packages\bitsandbytes\nn\triton_based_modules.py", line 6, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "D:\ai\ComfyUI\python\lib\site-packages\bitsandbytes\triton\dequantize_rowwise.py", line 12, in <module>
    import triton
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\__init__.py", line 20, in <module>
    from .runtime import (
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, autotune, heuristics)
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\runtime\autotuner.py", line 9, in <module>
    from ..testing import do_bench, do_bench_cudagraph
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\testing.py", line 7, in <module>
    from . import language as tl
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\language\__init__.py", line 4, in <module>
    from . import math
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\language\math.py", line 1, in <module>
    from . import core
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\language\core.py", line 10, in <module>
    from ..runtime.jit import jit
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\runtime\jit.py", line 12, in <module>
    from ..runtime.driver import driver
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\runtime\driver.py", line 1, in <module>
    from ..backends import backends
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\backends\__init__.py", line 50, in <module>
    backends = _discover_backends()
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\backends\__init__.py", line 43, in _discover_backends
    compiler = _load_module(name, os.path.join(root, name, 'compiler.py'))
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\backends\__init__.py", line 12, in _load_module
    spec.loader.exec_module(module)
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\backends\amd\compiler.py", line 2, in <module>
    from triton._C.libtriton import ir, passes, llvm, amd
ImportError: DLL load failed while importing libtriton: 动态链接库(DLL)初始化例程失败。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ai\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI-CatvtonFluxWrapper\__init__.py", line 1, in <module>
    from .nodes import *
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI-CatvtonFluxWrapper\nodes.py", line 6, in <module>
    from .pipeline_flux_fill import FluxFillPipeline
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI-CatvtonFluxWrapper\pipeline_flux_fill.py", line 26, in <module>
    from diffusers.loaders import FluxLoraLoaderMixin, FromSingleFileMixin, TextualInversionLoaderMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\utils\import_utils.py", line 843, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\utils\import_utils.py", line 855, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.loaders.lora_pipeline because of the following error (look up to see its traceback):
DLL load failed while importing libtriton: 动态链接库(DLL)初始化例程失败。

plz help

**Comment by lujiazho** [comment]
This seems to be related to diffusers installation problem. Have you upgraded diffusers to the latest version?
