### ISSUE TITLE
cannot install the node

### ISSUE THREAD

**Issue by judy544422** [lujiazho/ComfyUI-CatvtonFluxWrapper#7]
![image](https://github.com/user-attachments/assets/8beb3016-8cf8-43f3-93d5-59255d282df6)
![image](https://github.com/user-attachments/assets/7c8b05f2-27ff-4013-9569-8ea836f8669b)
even i try to fix， it still  can not be installed

**Comment by GymkhanaSports** [comment]
Same problem here. Made the token too.  But do not understand the environment variable process (newbie here). Probably that is the issue here.
![Untitled-1](https://github.com/user-attachments/assets/6f0d019c-87d3-40b5-9270-cd0952ee1a89)

**Comment by JimmyMo123** [comment]
pip install --upgrade diffusers==0.31.0

**Comment by lujiazho** [comment]
> ![image](https://private-user-images.githubusercontent.com/172378575/391860488-8beb3016-8cf8-43f3-93d5-59255d282df6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzkzOTgsIm5iZiI6MTczMzI3OTA5OCwicGF0aCI6Ii8xNzIzNzg1NzUvMzkxODYwNDg4LThiZWIzMDE2LThjZjgtNDNmMy05M2Q1LTU5MjU1ZDI4MmRmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwMjI0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTY4OTZmYzUwZDhlMWJhMTkxZDAxM2E1Y2IyNTQxMWVmODg4M2NjOWVjNTg1ODk5Y2QyNmI5YzY3MTMyODJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Y6CHi-KPdjuo5ag3LI7fWxyx8trXNzh4kW0zRPFUIMg) ![image](https://private-user-images.githubusercontent.com/172378575/391860889-7c8b05f2-27ff-4013-9569-8ea836f8669b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzkzOTgsIm5iZiI6MTczMzI3OTA5OCwicGF0aCI6Ii8xNzIzNzg1NzUvMzkxODYwODg5LTdjOGIwNWYyLTI3ZmYtNDAxMy05NTY5LThlYTgzNmY4NjY5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQwMjI0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzEzMTM2Y2I2ZDA2M2VhZDkzMDZlZTFjMTFjZGQwNzkwYTU4ZWE5YzMwNDMwYzMyM2QyYWVhZDIyODdhNmZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8-79B6VTPRpDE-VkrFiJIo342mYDT1LLlCY1bHUgEKU) even i try to fix， it still can not be installed

Can you show some errors so we can help with?

**Comment by GymkhanaSports** [comment]
1- Install for custom nodes - Restart.
2- Import failed.
3- Try fix - Restart.
4- Import failed. Uninstall - Restart.
5- Import failed.
This is the only message for the catvton flux node, i keep getting. I suspect that i have not performed some sort of requirement. 

![1](https://github.com/user-attachments/assets/a9af6574-29b7-4973-b609-9d9b29e73826)

**Comment by lujiazho** [comment]
Can you try to use the updated workflow? The LoadCatvtonFluxLoRA node is deprecated.

**Comment by GymkhanaSports** [comment]
I used the updated workflow. Below is the dump regarding wrapper and the error given by comfyui.
DUMP:
----------------------------------------------------------------------
Install custom node 'ComfyUI-CatvtonFluxWrapper'
Install: ['https://github.com/lujiazho/ComfyUI-CatvtonFluxWrapper']
Download: git clone 'https://github.com/lujiazho/ComfyUI-CatvtonFluxWrapper'
[!]
100%|██████████| 86.0/86.0 [00:03<00:00, 21.68it/s]
100%|██████████| 86.0/86.0 [00:03<00:00, 21.68it/s]
100%|██████████| 85.0/85.0 [00:04<00:00, 20.89it/s]
100%|██████████| 85.0/85.0 [00:04<00:00, 20.89it/s]
100%|██████████| 86.0/86.0 [00:04<00:00, 19.75it/s]
100%|██████████| 86.0/86.0 [00:04<00:00, 19.75it/s]
100%|██████████| 48.0/48.0 [00:04<00:00, 10.89it/s]
100%|██████████| 48.0/48.0 [00:04<00:00, 10.89it/s]
100%|██████████| 48.0/48.0 [00:09<00:00,  5.32it/s]
Installation was successful.
After restarting ComfyUI, please refresh the browser.
----------------------------------------------------------------------
Loaded ImpactPack nodes from C:\Users\Amena\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
Traceback (most recent call last):
  File "C:\Users\Amena\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Amena\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CatvtonFluxWrapper\__init__.py", line 1, in <module>
    from .nodes import *
  File "C:\Users\Amena\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CatvtonFluxWrapper\nodes.py", line 6, in <module>
    from .pipeline_flux_fill import FluxFillPipeline
  File "C:\Users\Amena\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CatvtonFluxWrapper\pipeline_flux_fill.py", line 26, in <module>
    from diffusers.loaders import FluxLoraLoaderMixin, FromSingleFileMixin, TextualInversionLoaderMixin
ImportError: cannot import name 'FluxLoraLoaderMixin' from 'diffusers.loaders' (C:\Users\Amena\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\__init__.py)

Cannot import C:\Users\Amena\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CatvtonFluxWrapper module for custom nodes: cannot import name 'FluxLoraLoaderMixin' from 'diffusers.loaders' (C:\Users\Amena\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\__init__.py)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
![2](https://github.com/user-attachments/assets/8b42acb5-b919-44ad-82d8-a3371ed2f3be)

**Comment by lujiazho** [comment]
Try update the diffusers: pip install --upgrade diffusers

**Comment by Falkonar** [comment]
How to install this node ? diffuses are up to date. Just when loading wf sampler node is red.

**Comment by GymkhanaSports** [comment]
> Try update the diffusers: pip install --upgrade diffusers

Got it to work. Deleted everything. Installed from scratch with all the updated latest components and latest downloads. Took a lot of time but it worked. 
Thanks for the help and continuous feedback.

**Comment by Falkonar** [comment]
> > Try update the diffusers: pip install --upgrade diffusers
> 
> Got it to work. Deleted everything. Installed from scratch with all the updated latest components and latest downloads. Took a lot of time but it worked. Thanks for the help and continuous feedback.

Did you install node on ComfyUI portable latest version? For me installing quick and loads with no errors but sampler node is red and not active.

**Comment by GymkhanaSports** [comment]
> > > Try update the diffusers: pip install --upgrade diffusers
> > 
> > 
> > Got it to work. Deleted everything. Installed from scratch with all the updated latest components and latest downloads. Took a lot of time but it worked. Thanks for the help and continuous feedback.
> 
> Did you install node on ComfyUI portable latest version? For me installing quick and loads with no errors but sampler node is red and not active.

Yes, i installed the latest version of portable comfyui. Then installed the node and it worked.
